Repository bh-coders/trip-planer, pull requests merged in 2024-03, with the labels that each got.

#110 #30 frontend design attraction view panel for user interface
  mobile/android/app/build.gradle
  mobile/components/views/Attractions/AddNew/AddNew.tsx
  mobile/components/views/Attractions/AddNew/AttractionForm.tsx
  mobile/components/views/Attractions/AddNew/OpeningHour.tsx
  mobile/components/views/Attractions/AddNew/components/Hours.tsx
  mobile/components/views/Attractions/AddNew/styles.ts
  mobile/components/views/Attractions/Review/AddNew.tsx
  mobile/components/views/Attractions/Review/AttractionReviewForm.tsx
  mobile/components/views/Attractions/Review/Edit.tsx
  mobile/components/views/Attractions/Review/styles.ts
  mobile/components/views/Attractions/Router.tsx
  mobile/components/views/Attractions/Search/AttractionModal.tsx
  mobile/components/views/Attractions/Search/Search.tsx
  mobile/components/views/Attractions/Search/api/apiMock.ts
  mobile/components/views/Attractions/Search/api/attractionsApi.ts
  mobile/components/views/Attractions/Search/components/FiltersModal.tsx
  mobile/components/views/Attractions/Search/styles.ts
  mobile/components/views/Attractions/api/attractionsApi.ts
  mobile/components/views/Attractions/api/fake/apiMock.ts
  mobile/components/views/Attractions/tools/openingHourMapper.js
  mobile/components/views/Attractions/types.ts
  mobile/components/views/Attractions/utils/restUtils.ts
  mobile/components/views/common/AttractionDetail.tsx
  mobile/components/views/common/components/details/edit/EditSubMenu.tsx
  mobile/components/views/common/components/details/review/AtrractionReviewTile.tsx
  mobile/components/views/common/components/details/review/FilterTile.tsx
  mobile/components/views/common/components/details/review/ReviewTile.tsx
  mobile/components/views/common/components/details/review/ReviewsModal.tsx
  mobile/components/views/common/components/details/review/SortTile.tsx
  mobile/components/views/common/components/details/review/styles.ts
  mobile/components/views/common/styles.ts
  mobile/package-lock.json
  mobile/package.json
  mobile/resources/images/house.jpg
  mobile/resources/images/tree.jpg
  mobile/resources/images/water.jpg
  mobile/routers/components/DrawnerContent.tsx
  mobile/routers/components/MainRouter.tsx
Labels: Frontend

#119 #118 hotfix/backend-fix-dev-branch-after-users-profiles-issue: repair files conf
  .gitignore
  README.DEV.md
  backend/.env.local
  backend/.gitignore
  backend/docker/redis/Dockerfile
  backend/requirements.txt
  backend/src/auth/routes/auth_router.py
  backend/src/auth/schemas/__init__.py
  backend/src/auth/services/auth_service.py
  docker-compose.dev.yml
Labels: critical/hotfix

#123 #120 add profiles do development docker
  README.DEV.md
  backend/.env.local
  backend/.env.template
  backend/docker/Dockerfile
  commands/debug.sh
  commands/load-env.sh
  docker-compose.dev.yml
  docker-compose.yml
Labels: Backend
